version: "2"
services:
    snowflake:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SNOWFLAKE_DOWNLOAD: $SNOWFLAKE_DOWNLOAD
        volumes:
            - ./data:/app/data
        environment:
            - SNOWFLAKE_USER
            - SNOWFLAKE_ACCOUNT
